spring.application.name=search_service
server.port=${SERVER_PORT:8083}

# API Path
server.servlet.context-path=/api/v1/search

# RabbitMQ Connection
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# exam_service
exam.events.exchange=${EXAM_EVENTS_EXCHANGE:exam.events}
exam.events.file-uploaded-routing-key=${EXAM_EVENTS_FILE_UPLOADED_ROUTING_KEY:exam.source.uploaded}
search.events.queue=${SEARCH_EVENTS_QUEUE:search.events.queue}

# B?n k?t qu? l?i cho exam_service
search.events.ai-extracted-routing-key=${SEARCH_EVENTS_AI_EXTRACTED_ROUTING_KEY:search.ai.extracted}

# Elasticsearch Connection
spring.elasticsearch.uris=${ELASTICSEARCH_URL:http://localhost:9200}

# MinIO Connection
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:admin}
minio.secret-key=${MINIO_SECRET_KEY:password}
minio.bucket-name=${MINIO_BUCKET_NAME:exam-sources}

# Spring AI - Google Gemini
gemini.api.key=${GEMINI_API_KEY:AQ.Ab8RN6K9uQ-FQRoMxavgtLRKy_zEp28x-KQrPguRBBe5kvQ_rw}

# Logging
logging.level.org.springframework.amqp=INFO
logging.level.org.springframework.data.elasticsearch=INFO